replicaCount: 1
image:
  repository: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY_NAME}
  pullPolicy: IfNotPresent
  tag: "{{ .Values.imageTag }}"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:  
  create: true  
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "flask.{{ .Values.ingressIp }}.nip.io"
      paths:
        - path: /tasks
          pathType: ImplementationSpecific
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
